name: Branch Pattern Example

on:
  push:
    branches:
      - main       # Trigger on pushes to the 'main' branch
      - feature    # Trigger on pushes to featur 

jobs:
  branch-check:
    runs-on: ubuntu-latest

    steps:
      - name: Display branch info
        run: echo "Branch:${{ github.ref_name }}"
